language: node_js
node_js:
   - "8"
cache:
  yarn: true
  directories:
  - $HOME/.npm
script:
  - npm test
  - CI="" npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "shifra-frontend-develop"
    local_dir: build
    skip_cleanup: true
    region: ap-southeast-2
    on:
      repo: ShifraIO/shifra-frontend
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "shifra-frontend-master"
    local_dir: build
    skip_cleanup: true
    region: ap-southeast-2
    on:
      repo: ShifraIO/shifra-frontend
      branch: master
